name: Windows (Direct3D 11)

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Get Submodules
      run: git submodule update --init --recursive
    - name: setup Node.js
      uses: actions/setup-node@v1.4.2
    - name: setup MSbuild
      uses: microsoft/setup-msbuild@v1
    - name: kromx
      run: node Kromx/make -g direct3d11
    - name: Unpack v8_monolith
      uses: DuckSoft/extract-7z-action@v1.0
      with:
        pathSource: Kromx/v8/libraries/win32/release/v8_monolith.7z
        pathTarget: Kromx/v8/libraries/win32/release/
    - name: Kinc
      run: cd Kromx && node Kinc/make -g direct3d11
      shell: cmd
    - name: MSbuild
      run: msbuild Kromx\build\Krom.sln -property:Configuration=Release -verbosity:diag
      shell: cmd
    - name: copy build files
      uses: canastro/copy-file-action@master
      with:
        source: "Kromx/build/x64/"
        target: "build/Krom"
    - name: publish build
      uses: actions/upload-artifact@v2
      with:
        path: build/krom
